#!/bin/bash

cd /dependencies || exit
# for dir in */
# Install projects with setup.py
for dir in  nsaph-utils data-platform census
do
  echo "Installing " $dir
  pushd $dir || exit
  pip3 install .
  popd || exit
done
cd ~ || exit
wget https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh -O anaconda.sh
chmod a+x ./anaconda.sh
./anaconda.sh -b -p ${HOME}/anaconda
pip3 uninstall -y typing
cd /dependencies/ || exit
export PATH=${HOME}/anaconda/condabin:$PATH
export CONDA_ENVFILE=$CONDA_ENV.yml
if [ -f "${CONDA_ENVFILE}" ] ;
then
  echo 'installing env from file'
  conda env create -f ${CONDA_ENVFILE} --prefix=${HOME}/${CONDA_ENV}
  exit
else
  echo 'installing default env'
  for cenv in NSAPHclimate census
  do
    conda create -y --name $cenv python=3.8
    conda install -y -c r r -n $cenv
  done
  exit
fi
echo 'build ended'