#!/bin/sh

cd /cwl-airflow
sed -ie 's#apache-airflow==2.0.1#apache-airflow==2.0.2#g' setup.py
pip3 install .
pip3 install cwlref-runner
pip3 install --upgrade apache-airflow-providers-google
wget https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh -O ~/anaconda.sh
bash ~/anaconda.sh -b -p $HOME/anaconda
