#!/bin/bash

echo "Installing Anaconda"
echo https_proxy=${https_proxy}   HTTPS_PROXY="${HTTPS_PROXY}"
wget https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh -O anaconda.sh
chmod a+x ./anaconda.sh
./anaconda.sh -b -p ${HOME}/anaconda
export PATH=${HOME}/anaconda/condabin:$PATH
pip3 uninstall -y typing
cd /dependencies/ || exit
if [ -f "${CONDA_ENVFILE}" ] ;
then
  echo "Not yet implemented"
  exit 1
else
  echo 'installing default conda environments'
  for cenv in NSAPHclimate census
  do
    echo $cenv
    #export prefix=${HOME}/anaconda/envs/${cenv}
    #conda create -y --name $cenv  python=3.8
    conda env create -f ${cenv}.yaml 
    source /root/anaconda/etc/profile.d/conda.sh
    echo 'from /root/anaconda/etc/profile.d/conda.sh'
    conda activate ${cenv}
    echo "Installing conda packages"
    conda install -y -c conda-forge psycopg2 apache-airflow-providers-postgres apache-airflow-providers-mysql numpy scipy apache-airflow=2.0.1 dataclasses rpy2
    if command -v R &> /dev/null
    then
      echo "Installing R packages"
      R -e "install.packages('remotes')"
      R -e "remotes::install_github('czigler/arepa')"
    fi
    #exit
  done
fi
