#!/bin/bash

echo "Installing local projects"
cd /dependencies || exit
# for dir in */
# Install projects with setup.py
for dir in  nsaph-utils data-platform census
do
  echo "Installing " $dir
  pushd $dir || exit
  pip3 install . || cd dist && pip3 install *.whl
  popd || exit
done
cd ~ || exit
echo 'Installed: local projects'