#!/bin/bash

cd /cwl-airflow
sed -ie 's#apache-airflow==2.0.1#apache-airflow==2.0.2#g' setup.py
pip3 install .
pip3 install --upgrade apache-airflow-providers-google
pip3 install cwlref-runner
cd ~
echo 'build ended'